### ISSUE TITLE
Include license file in the crate on crate.io

### ISSUE THREAD

**Issue by ghost** [rkyv/ptr_meta#1]
Hi, fedora would like to have the license include in the crate source and not have to download it separately if possible. Thanks.

**Comment by djkoloski** [comment]
Fixed by 870dc0d9234793e39cb4016542c55c04c317f479. Do you need a new version published? I don't have any source updates to make.

**Comment by ghost** [comment]
Yes that would be the way to propagate the fix to fedora. Thanks!

**Comment by djkoloski** [comment]
0.1.4 has been published to crates.io.
