### ISSUE TITLE
Release with updated syn?

### ISSUE THREAD

**Issue by branan** [rkyv/ptr_meta#3]
Howdy,

I'm looking through one of my projects hunting down big duplicate crates. `ptr_meta` is one of the ones left that's still on syn 1.0. It looks like it was bumped a few months ago, but a release was never cut.

Any chance of releasing, since it seems like other changes aren't particularly likely to land?

**Comment by djkoloski** [comment]
Sorry for the radio silence, do you need a specific version with syn bumped? I just finished some work on a new 0.3 version that addresses some changes to trait object vtable semantics, and that uses an updated version of syn.

**Comment by nicholasbishop** [comment]
I'm not the OP, but I'm also interested in a new release that updates the syn dep. Having that as part of an 0.3 version with other changes would not be a problem for me.

**Comment by djkoloski** [comment]
I just made a few more changes for the next version. I'm planning on cutting a new release soon, I just want to make sure that I get all the features I need for the next version of rkyv in before doing so. It should be relatively stable, so in a week or two I'll make a cut.

**Comment by djkoloski** [comment]
I just published `0.3.0-alpha.3` which is updated to syn 2. When 0.3.0 is released in full, it will also be updated.
